#include "glib-object.h"
#include "glib.h"
#include "glibconfig.h"
#include "gst/gstbin.h"
#include "gst/gstbus.h"
#include "gst/gstclock.h"
#include "gst/gstelement.h"
#include "gst/gstelementfactory.h"
#include "gst/gstmessage.h"
#include "gst/gstobject.h"
#include "gst/gstpipeline.h"
#include "gst/gstutils.h"
#include <stdio.h>
#include <gstreamer-1.0/gst/gst.h>

#ifdef __APPLE__
#include <TargetConditionals.h>
#endif

int tutorial_main(int argc, char *argv[]) {
    GstElement *pipeline, *source, *sink;
    GstElement *filter1, *convert1, *convert2;
    GstBus *bus;
    GstMessage *msg;
    GstStateChangeReturn ret;

    gst_init(&argc, &argv);

    // the first parameter is the type and the second parameter is the name
    // if passed NULL, gstreamer will name it regardless
    source = gst_element_factory_make("videotestsrc", "source");
    sink = gst_element_factory_make("autovideosink", "sink");
    filter1 = gst_element_factory_make("vertigotv", "filter1");
    convert1 = gst_element_factory_make("videoconvert", "convert1");
    convert2 = gst_element_factory_make("videoconvert", "convert2");

    pipeline = gst_pipeline_new("test-pipeline");

    if (!pipeline || !source || !sink || !filter1 || !convert1 || !convert2) {
        g_printerr("Not all elements could be created.\n");
        gst_object_unref(pipeline);
        return -1;
    }

    // adds elements to the pipeline (in no order), can even use gst_bin_add
    gst_bin_add_many(GST_BIN(pipeline), source, convert1, filter1, convert2, sink, NULL);
    // here order matters as we are linking the elements in the pipeline
    // ONLY ELEMENTS IN SAME BIN can be linked together, else it will return FALSE
    if (gst_element_link(source, convert1) != TRUE) {
        g_printerr("Elements could not be linked. 1\n");
        gst_object_unref(pipeline);
        return -1;
    }
    if (gst_element_link(convert1, filter1) != TRUE) {
        g_printerr("Elements could not be linked. 2\n");
        gst_object_unref(pipeline);
        return -1;
    }
    if (gst_element_link(filter1, convert2) != TRUE) {
        g_printerr("Elements could not be linked. 3\n");
        gst_object_unref(pipeline);
        return -1;
    }
    if (gst_element_link(convert2, sink) != TRUE) {
        g_printerr("Elements could not be linked. 4\n");
        gst_object_unref(pipeline);
        return -1;
    }


    // g_object_get and g_object_set comes from GObject in glib
    // both are used to set properties as key value pairs and end with NULL
    // NULL is used because it allows the last property to be checked if it is NULL or not
    g_object_set(source, "pattern", 0, NULL);
    // pattern property can be changed to try different test video patterns

    // all properties of an element could be found using gst-inspect-1.0

    ret = gst_element_set_state(pipeline, GST_STATE_PLAYING);
    if (ret == GST_STATE_CHANGE_FAILURE) {
        g_printerr("Unable to set the pipeline to the playing state.\n");
        gst_object_unref(pipeline);
        return -1;
    }

    // will block till error or EOS (End of stream)
    // Bus is responsible for delivering the GstMessages generated by the GstElements to the
    // application / code in order and to the application thread
    bus = gst_element_get_bus(pipeline);
    // Messages extracted from the bus synchronously (can be done in async as well using signals)
    msg = gst_bus_timed_pop_filtered(bus, GST_CLOCK_TIME_NONE, GST_MESSAGE_ERROR | GST_MESSAGE_EOS);

    if (msg != NULL) {
        GError *err;
        gchar *debug_info;

        switch (GST_MESSAGE_TYPE(msg)) {
            case GST_MESSAGE_ERROR:
                gst_message_parse_error(msg, &err, &debug_info);
                g_printerr("Error recieved from element %s: %s\n",
                        GST_OBJECT_NAME(msg->src), err->message);
                g_printerr("Debugging info: %s\n", debug_info ? debug_info : "none");
                g_clear_error(&err);
                break;

            case GST_MESSAGE_EOS:
                g_print("End of stream reached.\n");
                break;
            default:
                g_print("Unexpected message recieved.\n");
                break;
        }
        gst_message_unref (msg);
    }

    // Freeing Resources
    gst_object_unref (bus);
    gst_element_set_state (pipeline, GST_STATE_NULL);
    gst_object_unref (pipeline);

    return 0;
}

int main(int argc, char *argv[]) {
    printf("Hello World\n");

#if defined(__APPLE__) && TARGET_OS_MAC && !TARGET_OS_IPHONE
    return get_macos_main((GstMainFunc)tutorial_main, argc, argv, NULL);
#else
    return tutorial_main(argc, argv);
#endif
}
